### ISSUE TITLE
Please cache also json file

### ISSUE THREAD

**Issue by HolgerJeromin** [elgohr/EPEX-DE-History#1]
It would be nice if you could also cache the json data from
https://www.awattar.de/services/api

This also provides historic data so you could fetch old data or rebuild even historic yaml files.

**Comment by HolgerJeromin** [comment]
Ensoe could be interesting, too.
`https://m-transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=true&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=02.07.2023 00:00|CET|DAY&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET (UTC 1) / CEST (UTC 2)&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&resolution.values=PT60M`

**Comment by elgohr** [comment]
This repository does one thing and it does it good 🙂
